# Numpy

.numpy is general-purpose array processing package.
.numpy was created to work with multidimentional arrays.
.it is fundamental package for scientific computing with python.
.it is open source library.

In [1]:
#importing necessary library
!pip install numpy

import numpy as np

In [2]:
#Array creation

a=np.array(10)
type(a)

numpy.ndarray

In [3]:
#Zero dimentional array

In [4]:
z=np.array(10)

z.ndim

0

In [5]:
#one dimentional array

In [6]:
o=np.array([10,12,12,15])
o.ndim

1

In [7]:
#Two dimentional array

In [8]:
t=np.array([[10,10,12,14,15]])
t.ndim

2

In [9]:
#Three dimentional array

In [10]:
th=np.array([[[10,12,14,15,16]]])
th.ndim

3

In [11]:
#Change the data type of array elements

In [12]:
a=np.array([10,15,52,54])
a.dtype

dtype('int32')

In [13]:
a=np.array([10,15,52,54],dtype='float')
a.dtype

dtype('float64')

# Other ways of creating an array

In [14]:
#arrange

In [16]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
#linspace

In [18]:
b=np.linspace(1,5,15)
b

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
       3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ])

In [19]:
#zeros

In [20]:
z=np.zeros([2,2])
z

array([[0., 0.],
       [0., 0.]])

In [21]:
#ones

In [22]:
o=np.ones([5,5])
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
#random

In [24]:
r=np.random.rand(5,5)
r

array([[0.33362439, 0.94947872, 0.03190672, 0.80787789, 0.63399947],
       [0.0116653 , 0.77671643, 0.73368002, 0.77206963, 0.97772525],
       [0.26411001, 0.0304475 , 0.29123896, 0.88409616, 0.90206431],
       [0.22567968, 0.98129013, 0.28003763, 0.61133452, 0.63893692],
       [0.76563985, 0.78040045, 0.83978964, 0.86797071, 0.25084677]])

In [27]:
r=np.random.randint(5, size=10)
r

array([4, 4, 0, 0, 2, 3, 4, 0, 1, 2])

# Slicing and indexing of arrays

In [28]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
a[0,0]

1

In [30]:
a[1,2]

6

In [31]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
a[0,1:]

array([2, 3])

In [33]:
a[0:,1:]

array([[2, 3],
       [5, 6]])

In [34]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
#1 and 6
a[[0,1],[0,2]]

array([1, 6])

In [36]:
#3and 4

In [37]:
a[[0,1],[0,2]]

array([1, 6])

# Reshaping the arrays

In [38]:
a=np.random.rand(5,2)
a

array([[0.94076997, 0.86177793],
       [0.41939255, 0.34300685],
       [0.29792478, 0.64118885],
       [0.54455102, 0.78332928],
       [0.71082379, 0.54985407]])

In [39]:
a.reshape(2,5)

array([[0.94076997, 0.86177793, 0.41939255, 0.34300685, 0.29792478],
       [0.64118885, 0.54455102, 0.78332928, 0.71082379, 0.54985407]])

In [40]:
a.reshape(10,1)

array([[0.94076997],
       [0.86177793],
       [0.41939255],
       [0.34300685],
       [0.29792478],
       [0.64118885],
       [0.54455102],
       [0.78332928],
       [0.71082379],
       [0.54985407]])

In [41]:
a.reshape(1,10)

array([[0.94076997, 0.86177793, 0.41939255, 0.34300685, 0.29792478,
        0.64118885, 0.54455102, 0.78332928, 0.71082379, 0.54985407]])

In [42]:
a.reshape(5,-1)

array([[0.94076997, 0.86177793],
       [0.41939255, 0.34300685],
       [0.29792478, 0.64118885],
       [0.54455102, 0.78332928],
       [0.71082379, 0.54985407]])

# Aggregate Function
.The Python numpy aggregate functions are sum,min,max,mean.average,product,median,SD,variance,percentile and corr.coef

In [43]:
a.min()

0.2979247760942505

In [44]:
a.std()

0.20661201733568949

In [45]:
a.var()

0.04268852570752325

In [46]:
a.mean()

0.6092619075916591

# Stacking

.stacking is used to join different arrays.
.vertical stacking
.Horizontal stacking

In [47]:
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,8,7])

In [48]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 4, 5, 6, 8, 7])

In [49]:
np.vstack([a,b])

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 8, 7]])